In [1]:
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(10, 25)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
np.arange(20, 30, 3)

array([20, 23, 26, 29])

In [5]:
np.arange(-15, 5, 4)

array([-15, -11,  -7,  -3,   1])

In [6]:
np.arange(start = -15,stop = 5, step = 4)

array([-15, -11,  -7,  -3,   1])

In [8]:
np.arange(step = 4,stop = 5, start = -15)

array([-15, -11,  -7,  -3,   1])

In [9]:
np.arange(20).reshape([2, 10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [12]:
np.arange(30).reshape([3, 10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [13]:
np.arange(40).reshape([4, 10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [17]:
np.arange(20).reshape([2, 2, 5])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [20]:
np.random.random((10,))

array([0.91598576, 0.58175237, 0.02407259, 0.65146583, 0.76392748,
       0.48982976, 0.12989258, 0.06596291, 0.38980199, 0.34815702])

In [22]:
np.random.seed(10)
np.random.random((10,)).reshape((2, 5))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981]])

In [23]:
np.random.seed(10)
np.random.random((10,)).reshape((2, 5))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981]])

In [27]:
np.random.seed(10)
np.random.randint(50, 80, (4, 3, 3))

array([[[59, 79, 54],
        [65, 50, 67],
        [77, 78, 75]],

       [[79, 66, 79],
        [67, 76, 58],
        [59, 50, 60]],

       [[58, 72, 54],
        [69, 66, 54],
        [65, 61, 72]],

       [[74, 61, 76],
        [51, 58, 54],
        [64, 67, 69]]], dtype=int32)

In [28]:
np.random.seed(10)
np.random.randint(50, 80, (4, 3, 3)).flatten()

array([59, 79, 54, 65, 50, 67, 77, 78, 75, 79, 66, 79, 67, 76, 58, 59, 50,
       60, 58, 72, 54, 69, 66, 54, 65, 61, 72, 74, 61, 76, 51, 58, 54, 64,
       67, 69], dtype=int32)

In [29]:
np.arange(30).reshape(4, 10)

ValueError: cannot reshape array of size 30 into shape (4,10)