In [1]:
import numpy as np

In [2]:
first = np.array([[1, 2, 3], [4, 5, 6]])
first

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
first.dtype

dtype('int64')

In [4]:
first.ndim

2

In [5]:
first.shape

(2, 3)

In [6]:
second = np.array([[7, 8, 9], [10, 11, 12]])
second

array([[ 7,  8,  9],
       [10, 11, 12]])

In [7]:
second.shape

(2, 3)

In [8]:
first + second

array([[ 8, 10, 12],
       [14, 16, 18]])

In [9]:
first + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [10]:
first -2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [11]:
first * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [12]:
first / 3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [13]:
first

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
first[1, 1]

np.int64(5)

In [15]:
first[1, 2]

np.int64(6)

In [16]:
first[0, 2]

np.int64(3)

In [17]:
first[1, 0]

np.int64(4)

In [18]:
third = np.array([[44, 55, 66], [333, 43, 3], [55, 88, 9]])
third

array([[ 44,  55,  66],
       [333,  43,   3],
       [ 55,  88,   9]])

In [19]:
third.ndim

2

In [20]:
third[0, 2]

np.int64(66)

In [21]:
third[2, 0]

np.int64(55)

In [22]:
third[2, 1]

np.int64(88)

In [24]:
np.concatenate((first, second))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
np.concatenate((first, second), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [31]:
one_d = np.concatenate((np.array([1, 2, 3, 4]), np.array([5, 6, 7, 8])))
one_d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
one_d[4,]

np.int64(5)