In [6]:
import numpy as np

## 1. Calculating Total Revenue

In [6]:
prices = np.array([19.99, 29.99, 14.99, 9.99, 24.99])
prices

array([19.99, 29.99, 14.99,  9.99, 24.99])

In [9]:
quantities = np.array([10, 5, 8, 12, 3])
quantities

array([10,  5,  8, 12,  3])

In [11]:
revenue_per_product = prices * quantities
revenue_per_product

array([199.9 , 149.95, 119.92, 119.88,  74.97])

In [12]:
total_revenue = np.sum(revenue_per_product)
total_revenue

np.float64(664.62)

## 2. Analyzing Blog Post Stats

In [14]:
views = np.array([1000, 500, 800, 1200, 300, 600])
views

array([1000,  500,  800, 1200,  300,  600])

In [15]:
max_views = np.max(views)
max_views

np.int64(1200)

In [19]:
min_views = np.min(views)
min_views

np.int64(300)

In [27]:
average_views = np.mean(views)
average_views

np.float64(733.3333333333334)

In [28]:
average_views = np.round(np.mean(views), 2)
average_views

np.float64(733.33)

In [29]:
total_views = sum(views)
total_views

np.int64(4400)

## 3. Splitting Order into Batches

In [30]:
order_ids = np.array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009])
order_ids

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009])

In [31]:
batches = np.split(order_ids, 3)
batches

[array([1001, 1002, 1003]),
 array([1004, 1005, 1006]),
 array([1007, 1008, 1009])]

In [33]:
for batch in batches:
    print(batch)

[1001 1002 1003]
[1004 1005 1006]
[1007 1008 1009]


In [36]:
for batch in batches:
    print("First element in the batch: ", batch[0])
    print("Second element in the batch: ", batch[1])

First element in the batch:  1001
Second element in the batch:  1002
First element in the batch:  1004
Second element in the batch:  1005
First element in the batch:  1007
Second element in the batch:  1008


In [39]:
#Enumerate - возвращает последовательность кортежей
for i, batch in enumerate(batches):
    print(f"Batch number {i}")
    print("First element in the batch: ", batch[0])
    print("Second element in the batch: ", batch[1])
    print('')

Batch number 0
First element in the batch:  1001
Second element in the batch:  1002

Batch number 1
First element in the batch:  1004
Second element in the batch:  1005

Batch number 2
First element in the batch:  1007
Second element in the batch:  1008



## 4. Categorizing Product Ratings

In [40]:
ratings = np.array([4.5, 3.2, 2.8, 5.0, 4.1, 3.9, 2.5, 4.7])
ratings

array([4.5, 3.2, 2.8, 5. , 4.1, 3.9, 2.5, 4.7])

In [41]:
positive_ratings = ratings[ratings>=4.0]
positive_ratings 

array([4.5, 5. , 4.1, 4.7])

In [43]:
negative_ratings = ratings[ratings<4.0]
negative_ratings 

array([3.2, 2.8, 3.9, 2.5])

## 5. Calculate Total and Average quantities sold

In [44]:
# Each column is specific product (we have 4 products)
# Each row is specific order (we have 2 orders)
order_quantities = np.array([[5, 3, 2, 7], [10, 6, 3, 9]])
order_quantities

array([[ 5,  3,  2,  7],
       [10,  6,  3,  9]])

In [46]:
# Quantities of the sales per product
total_quantities_sold = np.sum(order_quantities, axis =0)
total_quantities_sold

array([15,  9,  5, 16])

In [48]:
# Quantities of the sales per order
total_products_per_order = np.sum(order_quantities, axis =1)
total_products_per_order

array([17, 28])

In [51]:
# Average quantities per product across all orders
avarage_quantities_sold = np.mean(order_quantities, axis = 0)
avarage_quantities_sold

array([7.5, 4.5, 2.5, 8. ])

## 6. Calculate Average product Rating and Maximum rating per Category

In [52]:
#Each row is on product
# Each product is rated in 4 categories

product_ratings = np.array([
    [4.5, 3.2, 2.5, 5.0],
    [4.3, 3.8, 1.0, 4.8],
    [2.0, 3.6, 4.7, 0.5]
])
product_ratings

array([[4.5, 3.2, 2.5, 5. ],
       [4.3, 3.8, 1. , 4.8],
       [2. , 3.6, 4.7, 0.5]])

In [54]:
# Average rating in each category
average_rating_per_categories = np.round(np.mean(product_ratings, axis = 0), 2)
average_rating_per_categories

array([3.6 , 3.53, 2.73, 3.43])

In [57]:
# Average rating in each category
max_rating_per_product = np.round(np.max(product_ratings, axis = 0), 2)
max_rating_per_product

array([4.5, 3.8, 4.7, 5. ])

In [58]:
# Average rating in each category
min_rating_per_product = np.round(np.min(product_ratings, axis = 0), 2)
min_rating_per_product

array([2. , 3.2, 1. , 0.5])

## 7. Generation of the sample stock data

In [3]:
companies = ['Google', 'Microsoft', 'Apple']
days = ['Mon 1 April', 'Tue 2 April']
price_types = ['Open', 'Close', 'High', 'Low']

In [32]:
# shape will be (3, 2, 4)
np.random.seed(1)
stock_prices = np.round(np.random.random((len(companies), len(days), len(price_types))), 3)
stock_prices

array([[[0.417, 0.72 , 0.   , 0.302],
        [0.147, 0.092, 0.186, 0.346]],

       [[0.397, 0.539, 0.419, 0.685],
        [0.204, 0.878, 0.027, 0.67 ]],

       [[0.417, 0.559, 0.14 , 0.198],
        [0.801, 0.968, 0.313, 0.692]]])

In [10]:
stock_prices.shape

(3, 2, 4)

In [35]:
for index_axis_0, company in enumerate(companies):
    print(f"Stock prices for the {company}: ")
    
    for index_axis_1, day in enumerate(days):
        print(f'Day: {day}') 
        
        for index_axis_2, price_type in enumerate(price_types):
            print(f'{price_type} Price: {stock_prices[index_axis_0, index_axis_1, index_axis_2]}')
            
        print('')
    print('')

Stock prices for the Google: 
Day: Mon 1 April
Open Price: 0.417
Close Price: 0.72
High Price: 0.0
Low Price: 0.302

Day: Tue 2 April
Open Price: 0.147
Close Price: 0.092
High Price: 0.186
Low Price: 0.346


Stock prices for the Microsoft: 
Day: Mon 1 April
Open Price: 0.397
Close Price: 0.539
High Price: 0.419
Low Price: 0.685

Day: Tue 2 April
Open Price: 0.204
Close Price: 0.878
High Price: 0.027
Low Price: 0.67


Stock prices for the Apple: 
Day: Mon 1 April
Open Price: 0.417
Close Price: 0.559
High Price: 0.14
Low Price: 0.198

Day: Tue 2 April
Open Price: 0.801
Close Price: 0.968
High Price: 0.313
Low Price: 0.692


